# See argocd/platform-root.yaml for overrides
clusterRouterDomain: example.cluster.com

gitHost: https://github.com
gitOrg: smongiar
gitRef: first-test
gitToken: ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
gitlabToken: XXXX
githubClientId: XXXX
gitlabClientId: XXXX
githubSecret: XXXX
gitlabSecret: XXXX

authClientSecret: replaceme
authSessionSecret: replaceme
