clusterRouterDomain: apps.developer-hub.fuse.integration-qe.com
auth:
  sessionSecret: Q72XbDKY8IcNSNzAQjVwa3xmh4lfdvzG
  keycloakUrl: https://keycloak-keycloak.apps.developer-hub.fuse.integration-qe.com
  keycloakRealm: backstage
  clientId: backstage
  clientSecret: my-secret
git:
  token: gitaccesstoken
  org: jboss-fuse-qe
  clientId: githubclientid
  secret:  githubsecret
gitlab:
  token: gitlabaccesstoken
  clientId: gitlabclientid
  secret: gitlabsecret