apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhdh.rhdh-operator: ''
  name: rhdh
  namespace: rhdh-operator
spec:
  channel: fast-1.4
  installPlanApproval: Automatic
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
